package entity;

public class CpInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.level
     *
     * @mbggenerated
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.secret
     *
     * @mbggenerated
     */
    private String secret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cp_info.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cp_info
     *
     * @mbggenerated
     */
    public CpInfo(Integer id, String name, Byte level, String secret, String ip) {
        this.id = id;
        this.name = name;
        this.level = level;
        this.secret = secret;
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.id
     *
     * @return the value of cp_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.name
     *
     * @return the value of cp_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.level
     *
     * @return the value of cp_info.level
     *
     * @mbggenerated
     */
    public Byte getLevel() {
        return level;
    }
    public void setLevel(Byte level) {
        this.level = level;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.secret
     *
     * @return the value of cp_info.secret
     *
     * @mbggenerated
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cp_info.ip
     *
     * @return the value of cp_info.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }
}