package entity;

import java.util.Date;

public class OrderRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.phonenum
     *
     * @mbggenerated
     */
    private String phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.spid
     *
     * @mbggenerated
     */
    private String spid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.pcpid
     *
     * @mbggenerated
     */
    private String pcpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.remoteip
     *
     * @mbggenerated
     */
    private String remoteip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.ordertype
     *
     * @mbggenerated
     */
    private Integer ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbggenerated
     */
    public OrderRecord(Integer id, String phonenum, String spid, String pcpid, String remoteip, Integer ordertype, Date createtime) {
        this.id = id;
        this.phonenum = phonenum;
        this.spid = spid;
        this.pcpid = pcpid;
        this.remoteip = remoteip;
        this.ordertype = ordertype;
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.id
     *
     * @return the value of order_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.phonenum
     *
     * @return the value of order_record.phonenum
     *
     * @mbggenerated
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.spid
     *
     * @return the value of order_record.spid
     *
     * @mbggenerated
     */
    public String getSpid() {
        return spid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.pcpid
     *
     * @return the value of order_record.pcpid
     *
     * @mbggenerated
     */
    public String getPcpid() {
        return pcpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.remoteip
     *
     * @return the value of order_record.remoteip
     *
     * @mbggenerated
     */
    public String getRemoteip() {
        return remoteip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.ordertype
     *
     * @return the value of order_record.ordertype
     *
     * @mbggenerated
     */
    public Integer getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.createtime
     *
     * @return the value of order_record.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }
}